AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Application Template for the comparison lambda

Globals:
    Function:
        Timeout: 60
        MemorySize: 1024
Resources:
    JavaLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./java/target/Lambda-1.0.jar
            Handler: io.viesure.blog.lambda.Lambda
            Runtime: java8
            Events:
                JavaApi:
                    Type: Api
                    Properties:
                        Path: /java
                        Method: POST
            Tags:
              viesure-blog: gatling-test
    PythonLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./python
            Handler: lambda.lambda_handler
            Runtime: python2.7
            Events:
                PythonApi:
                    Type: Api
                    Properties:
                        Path: /python
                        Method: POST
            Tags:
              viesure-blog: gatling-test
    NodeJsLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./node
            Handler: lambda.handler
            Runtime: nodejs8.10
            Events:
                NodeJsApi:
                    Type: Api
                    Properties:
                        Path: /nodejs
                        Method: POST
            Tags:
              viesure-blog: gatling-test
